name: Pytteliten Github Jobs
run-name: ${{ github.actor }} is running jobs on Pytteliten
on: [push, pull_request]
jobs:
  pl_size_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get size of PL mini
        run: bash build.sh
        shell: bash
  pl_verify_mini_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify PL mini builds
        run: make mini
        shell: bash
